name: Deploy App
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DO_WORKDIR: services/portfolio-colaia
      DO_STORAGE: $SERVER_WORKDIR/persistant
      DO_ACCESS: ${{ secrets.DO_VPS1_SSH_ACCESS }}
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v4
        
      # - name: Setup Node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: "23.1.0"

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DO_VPS1_SSH_PRIVATE_KEY }}
      - name: Test connection
        run: ssh $DO_ACCESS uname -r

      # - name: Copy server data
      #   run: |
      #     scp -r $DO_ACCESS:$DO_STORAGE/* /tmp
      #     ls -l /tmp

      # - name: Generate build
      #   run: |
      #     npm i
      #     npm run build
