name: Deploy App
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TOTP_SECRET: ${{ secrets.TOTP_SECRET }}
      SERVER_STORAGE: /
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "23.1.0"
          
      - run: npm i
      - run: npm run build
