name: Deploy App
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DO_WORKDIR: services/portfolio-colaia
      DO_STORAGE: services/portfolio-colaia/persistant
      DO_IP: ${{ secrets.DO_VPS1_SSH_IP }}
      DO_SSH: ${{ secrets.DO_VPS1_SSH_USER }}@${{ secrets.DO_VPS1_SSH_IP }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "23.1.0"

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DO_VPS1_SSH_PRIVATE_KEY }}

      - run: ssh-keyscan -H $DO_IP >> ~/.ssh/known_hosts

      - name: Prepare to Build
        run: scp -r $DO_SSH:$DO_STORAGE/* /tmp

      - name: Build
        run: |
          npm i
          npm run build

      - name: Prepare to Deploy
        run: |
          echo 'DO_STORAGE='$DO_STORAGE >> .env
          echo 'TOTP_SECRET='${{ secrets.TOTP_SECRET }} >> .env
          tar -czvf latest.tar.gz package.json package-lock.json next.config.ts .env .next/

      - name: Deploy
        run: |
          scp -r latest.tar.gz $DO_SSH:$DO_STORAGE
          ssh $DO_SSH
          cd $DO_STORAGE
          mkdir tmp
          cd tmp
          tar -xzvf latest.tar.gz --overwrite
          # npm i
