name: Deploy App
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DO_WORKDIR: services/portfolio-colaia
      DO_STORAGE: services/portfolio-colaia/persistant
      DO_IP: ${{ secrets.DO_VPS1_SSH_IP }}
      DO_SSH: ${{ secrets.DO_VPS1_SSH_USER }}@$DO_IP
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v4
        
      # - name: Setup Node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: "23.1.0"

      - name: Test ping with resolved address
        run: ping -c 4 $DO_IP || true

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DO_VPS1_SSH_PRIVATE_KEY }}
      
      - name: Add known host
        run: ssh-keyscan -H $DO_IP >> ~/.ssh/known_hosts
        
      - name: Test connection
        # run: ssh -o StrictHostKeyChecking=no -v root@46.101.29.4 uname -r
        run: ssh -v $DO_SSH uname -r

      # - name: Copy server data
      #   run: |
      #     scp -r $DO_ACCESS:$DO_STORAGE/* /tmp
      #     ls -l /tmp

      # - name: Generate build
      #   run: |
      #     npm i
      #     npm run build
