name: Deploy to VPS1
on:
  push:
    branches:
      - main
jobs:
  workflow:
    runs-on: ubuntu-latest
    env:
      PERSISTANT: /tmp

      DO_WORKDIR: services/action-test
      DO_PERSISTANT: services/portfolio-colaia/persistant
      DO_IP: ${{ secrets.DO_VPS1_SSH_IP }}
      DO_SSH: ${{ secrets.DO_VPS1_SSH_USER }}@${{ secrets.DO_VPS1_SSH_IP }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "23.1.0"

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DO_VPS1_SSH_PRIVATE_KEY }}

      - name: Add known hosts
        run: ssh-keyscan -H $DO_IP >> ~/.ssh/known_hosts

      - name: Download latest data
        run: scp -r $DO_SSH:$DO_PERSISTANT/* $PERSISTANT

      - name: Build
        run: |
          npm i
          npm run build

      - name: Upload
        run: |
          echo 'PERSISTANT='$DO_PERSISTANT >> .env
          echo 'TOTP_SECRET='${{ secrets.TOTP_SECRET }} >> .env
          tar -czvf latest.tar.gz package.json package-lock.json next.config.ts .env .next/ node_modules &&
          scp -r latest.tar.gz $DO_SSH:$DO_WORKDIR

      - name: Deploy
        run: |
          ssh $DO_SSH <<EOF
            cd $DO_WORKDIR
            tar -xzvf latest.tar.gz
          EOF
